name: Publish Docker Image

on:
  workflow_dispatch:

env:
  IMAGE_TAG: dapiaproject/anomaly-detection:0.${{github.run_number}}

jobs:
  push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        run: docker login -u ${{ secrets.DOCKER_HUB_USR }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build
        run: docker build -t ${{ env.IMAGE_TAG }} -f ./Dockerfile .

      - name: Push
        run: docker push ${{ env.IMAGE_TAG }}